# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import test_pb2 as test__pb2


class InvoicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTxToBlockchain = channel.unary_unary(
                '/Invoicer/AddTxToBlockchain',
                request_serializer=test__pb2.CreateTx.SerializeToString,
                response_deserializer=test__pb2.CreateResponse.FromString,
                )
        self.GetLastBlock = channel.unary_unary(
                '/Invoicer/GetLastBlock',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=test__pb2.CreateResponse.FromString,
                )


class InvoicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTxToBlockchain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastBlock(self, request, context):
        """rpc GetUserTxHistory(User) returns ()
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvoicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTxToBlockchain': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTxToBlockchain,
                    request_deserializer=test__pb2.CreateTx.FromString,
                    response_serializer=test__pb2.CreateResponse.SerializeToString,
            ),
            'GetLastBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastBlock,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=test__pb2.CreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Invoicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Invoicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTxToBlockchain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Invoicer/AddTxToBlockchain',
            test__pb2.CreateTx.SerializeToString,
            test__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLastBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Invoicer/GetLastBlock',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            test__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
