# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x08\x43reateTx\x12\x15\n\rsenderAddress\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06pubKey\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"\"\n\x0e\x43reateResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"C\n\x0b\x42lockHeader\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x15\n\rHashPrevBlock\x18\x02 \x01(\x0c\x12\x0c\n\x04Time\x18\x03 \x01(\x03\"q\n\x05\x42lock\x12\x11\n\tblocksize\x18\x01 \x01(\x04\x12!\n\x0b\x62lockheader\x18\x02 \x01(\x0b\x32\x0c.BlockHeader\x12\x11\n\tTxCounter\x18\x03 \x01(\x04\x12\x1f\n\x0ctransactions\x18\x04 \x03(\x0b\x32\t.CreateTx2t\n\x08Invoicer\x12/\n\x11\x41\x64\x64TxToBlockchain\x12\t.CreateTx\x1a\x0f.CreateResponse\x12\x37\n\x0cGetLastBlock\x12\x16.google.protobuf.Empty\x1a\x0f.CreateResponseB\x17Z\x15trustedStorage/serverb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025trustedStorage/server'
  _CREATETX._serialized_start=43
  _CREATETX._serialized_end=125
  _CREATERESPONSE._serialized_start=127
  _CREATERESPONSE._serialized_end=161
  _BLOCKHEADER._serialized_start=163
  _BLOCKHEADER._serialized_end=230
  _BLOCK._serialized_start=232
  _BLOCK._serialized_end=345
  _INVOICER._serialized_start=347
  _INVOICER._serialized_end=463
# @@protoc_insertion_point(module_scope)
